name: Release binary artifacts

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Run linter
        run: cargo clippy
      - name: Publish
        run: cargo publish

  release:
    runs-on: ubuntu-latest

    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
